# Generated by Django 5.1.4 on 2024-12-19 16:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedcontent',
            name='file_content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file_content'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pics'),
        ),
    ]
