# Generated by Django 5.1.4 on 2024-12-20 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_storedcontent_file_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspace',
            name='custom_url',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='userspace',
            unique_together={('user', 'custom_url')},
        ),
    ]
