# Generated by Django 5.1.3 on 2024-12-18 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_url', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=50)),
                ('text_content', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='user_uploads/')),
                ('userspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.userspace')),
            ],
        ),
    ]
