# Generated by Django 5.1.4 on 2024-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_storedcontent_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedcontent',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file_content'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pic/'),
        ),
    ]
